# Enable MCUboot
SB_CONFIG_BOOTLOADER_MCUBOOT=y

# Disable NSIB to cut overhead
SB_CONFIG_SECURE_BOOT_APPCORE=n

# Overwrite-only upgrade mode (no swap partition)
SB_CONFIG_MCUBOOT_MODE_OVERWRITE_ONLY=y

# Skip signature verification (use SHA256 only for speed)
SB_CONFIG_BOOT_SIGNATURE_TYPE_NONE=y

# Disable Partition Manager, use DTS partitions instead
SB_CONFIG_PARTITION_MANAGER=n